### ISSUE TITLE
Method not accessible to Obj-C integrations

### ISSUE THREAD

**Issue by dsmith060** [adadaptedinc/ios-swift-sdk#14]
Can we please get a "@objc" on this line so that this method is available to integrations using Obj-C?

https://github.com/adadaptedinc/ios-swift-sdk/blob/1dc3a058132ba3832b28c2ca660ad2da9b082939/AASwiftSDK/Public/AdContent.swift#L128

**Comment by bclifton-aa** [comment]
Done. As we're moving to a monthly release schedule for the SDKs, this should be included in the March release. If an app needs this implementation sooner I can get a patch release out as well, just let me know-
